Repository xmm7360/xmm7360-pci, pull requests merged in 2021-03, with the labels that each got.

#47 add complete example for ubuntu 20.04
  README.md
Labels: documentation

#21 update readme with how to set pin
  README.md
Labels: documentation

#46 add dependencies to readme
  README.md
Labels: documentation

#72 Additional device support
  DEVICES.md
Labels: device-support

#75 Add config file for management script
  .gitignore
  README.md
  rpc/open_xdatachannel.py
  scripts/lte.sh
  xmm7360.ini.sample
Labels: enhancement

#74 tty_alloc_driver
  xmm7360.c
Labels: enhancement

#78 C Code Formatting + CI Workflow
  .clang-format
  .github/workflows/main.yml
  .gitignore
  INSTALLING.md
  Pipfile
  Pipfile.lock
  README.md
  rpc/mux.c
  rpc/xmm7360.h
  xmm7360.c
Labels: documentation, enhancement

#73 Create simple management script
  .gitignore
  INSTALLING.md
  README.md
  rpc/open_xdatachannel.py
  scripts/lte.sh
  xmm7360.ini.sample
Labels: enhancement

#66 Networkmanager/DBUS Interface
  examples/modem_reset.pl
  examples/xmm7360.service
  examples/xmm7360_status.pl
  rpc/open_xdatachannel.py
Labels: enhancement
